controller_list:
  - name: fake_rokae_group_controller
    type: $(arg fake_execution_type)
    joints:
      - left_arm_joint_1
      - left_arm_joint_2
      - left_arm_joint_3
      - left_arm_joint_4
      - left_arm_joint_5
      - left_arm_joint_6
      - left_arm_joint_7
  - name: fake_EE_group_controller
    type: $(arg fake_execution_type)
    joints:
      - left_arm_joint_7
initial:  # Define initial robot poses per group
  - group: rokae_group
    pose: home