sudo: true
dist: trusty
language:
  - generic
cache:
  - apt

jobs:
  include:
    - stage: OpenSceneGraph
    - script: ./install-dependencies.sh; ./install-osg.sh
    - stage: OpenRAVE
    - script: ./install-dependencies.sh; ./install-fcl.sh; ./install-openrave.sh
